#This script is generated by Pratik Padwal to calculate BMI using formula BMI = weight / (height ** 2)
height = float(input("Enter your height in meter\n"))
weight = float(input("Enter your weight in Kg\n"))
bmi = weight / (height ** 2)
#to make it user friendly,rounding BMI to the closest number.
Final_bmi = round(bmi)
print("Your BMI is" + " " + str(Final_bmi))