#This script is generated by Pratik Padwal to calculate BMI using formula BMI = weight / (height ** 2)
height = float(input("Enter your height in meter\n"))
weight = float(input("Enter your weight in Kg\n"))
bmi = weight / (height ** 2)
#to make it user friendly,rounding BMI to the closest number.
Final_bmi = round(bmi)
if Final_bmi < 18:
    print(f"your BMI is {Final_bmi} and you are underweight")
elif Final_bmi < 25:
    print(f"your BMI is {Final_bmi} and your weight is normal")
else:
    print(f"your BMI is {Final_bmi} and you are overweight")