#This script is generated by Pratik Padwal.
print("Welcome to the band name generator app")
city = input("what is your city name ?\n")
pet = input("what is your per name ?\n")
print("Your band name is " + city + " " + pet)